EMAIL = "prak1har@gmail.com"
EMAIL_PASSWORD = "xzsfcvtaqrfoxavg"

API_KEY = "eb80086ef12c49239705febc64252907"

USERS = """
{
  "master": { "password": "master123" },
  "client1": { "password": "client123" },
  "client2": { "password": "client123" }
}
"""